// layout.tsx
import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import { ClientThemeProvider } from "./components/ClientThemeProvider";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places,marker&v=weekly`}
          strategy="beforeInteractive"
        />
      </head>
      <body>
        <SessionProvider>
          <Navbar />
          <ClientThemeProvider>{children}</ClientThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
